### PR TITLE
fix lithic node socket timeout

### PR DESCRIPTION
**Pull request by tyleradams**
worked locally when I made the equivalent change to my core.js file
Needed to get https://docs.lithic.com/reference/postaccountholders working.

### CODE REVIEW

**Comment by rattrayalex** [comment]
@tyleradams thank you for this! We will probably make some further tweaks here soon, but appreciate the contribution in the meantime!

**Comment by tyleradams** [comment]
Thanks! When will it be released in a package?

**Comment by rattrayalex** [comment]
Shooting for later today!

**Comment by tyleradams** [comment]
Nope, just wanted KYB to work

**Comment by rattrayalex** [comment]
Got it, thanks! Was there a reason why you went with `freeSocketTimeout` over simply `timeout`? (the former will also adjust the latter, so it could have worked but only because it adjusted the `timeout`)

**Comment by tyleradams** [comment]
error was socket timeout, seemed natural
 Tyler

**Comment by rattrayalex** [comment]
Got it, thanks. We've published your change by the way! Thanks for it. We may adjust in the future.

**Pull request merged**
